### ISSUE TITLE
GeoViewUserToDisplayToGraphicLayer -  sortedDatas : nil exception on shape 

### ISSUE THREAD

**Issue by LANDAISB** [OpenSmock/GeoView#11]
I had a nil exception (gShapeA is nil) on method graphicalOrderSortBlock of GeoViewUserToDisplayToGraphicLayer.

Maybe due to concurrent access : comes from another thread (not UI).

**Comment by labordep** [comment]
Normally this is fixed in #16.
Can you confirm?

**Comment by labordep** [comment]
@LANDAISB can I close?
